#AMQ Configurations
anypoint-mq:
    # replace if mq url changed
    server-url: "https://mq-us-east-2.anypoint.mulesoft.com/api/v1"
    case-queue-name: "accelerator-salesforce-case-queue"
    case-dl-queue-name: "accelerator-salesforce-case-dl-queue"
    client-id: "b04536ac971a4f54b499ae6e0b641543"
    client-secret: "A3E6aA5fafc9416B952E45fE18148621"
    
#Salesforce Configurations    
sfdc:
    #replace with respective sfdc username
    userName: "tosudha85@gmail.com"
    token: "2rG5EPeppTf0EaQHl1FgO1RJe"
    password:  "Salesforce@314"     
    topicName: "All_Cases"
    #Replace with higher values to prevent duplicate cases from SFDC
    replayId: "1"
   
# Retry configuration
retry:
   amq: 
    delayMillisecs: "3000"
    numRetries: "3"
    
# Reconnect configuration
reconnection:
     amq:
      frequency: "2000"
      attempts: "2"
     sfdc:
      frequency: "3000"
      attempts: "3"  
      
# Customize the application messages in the below section    
application-msgs:
   # Before Connector logger message
   before-connector-call-message: "Before Connector Call"
   # After Connector logger message
   after-connector-call-message: "After Connector Call"
   # Local Exception Handler logger message
   local-exception-handler-message: "Exception has occured"
